
---
- name: Backup Nextcloud
  hosts: nextcloud
  remote_user: ansible
  become: yes
  become_user: www-data
  tasks:
  - name: Set maintanance mode
    shell: 'php /var/www/nextcloud/occ maintenance:mode --on'
  - name: create database dump
    mysql_db:
      login_user: '{{ lookup("env", "MYSQL_USERNAME")}}'
      login_password: '{{ lookup("env", "MYSQL_PASSWORD") }}'
      state: dump
      name: nextcloud
      target: /home/malte/backups/nextcloud-database.bak
  - name: borg backup
    shell: 'borg create ::{{ ansible_hostname }}-{{ ansible_date_time.iso8601_basic_short }} /var/www/nextcloud /data/nextcloud/ /home/malte/backups/nextcloud-database.bak'
    environment:
      BORG_REPO: '{{ lookup("env", "BORG_SERVER")}}'
      BORG_PASSPHRASE: '{{ lookup("env", "BORG_PASSWORD")}}'
  - name: borg prune
    shell: 'borg prune --prefix {{ ansible_hostname }} --keep-monthly 12'
    environment:
      BORG_REPO: '{{ lookup("env", "BORG_SERVER")}}'
      BORG_PASSPHRASE: '{{ lookup("env", "BORG_PASSWORD")}}'
  - name: Set maintanance mode off
    shell: php /var/www/nextcloud/occ maintenance:mode --off


