
---
- name: Backup Nextcloud
  hosts: nextcloud
  remote_user: ansible
  become: yes
  become_user: www-data
  tasks:
  - name: Set maintanance mode
    shell: 'php /var/www/nextcloud/occ maintenance:mode --on'
  - name: backup nextcloud
    shell: 'rsync -Aavx --delete /var/www/nextcloud/ /home/malte/backups/nextcloud'
  - name: backup user data
    shell: 'rsync -Aavx --delete /data/nextcloud/ root@serv:/volume1/timemachine/nextcloud/'
    become: yes
    become_user: root
  - name: backup data base
    mysql_db:
      login_user: '{{ lookup("env", "MYSQL_USERNAME")}}'
      login_password: '{{ lookup("env", "MYSQL_PASSWORD") }}'
      state: dump
      name: nextcloud
      target: /home/malte/backups/nextcloud-database.bak
  - name: Set maintanance mode off
    shell: php /var/www/nextcloud/occ maintenance:mode --off


