---
- name: Plex service
  hosts: serv
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
    - name: Start plex service
      community.docker.docker_compose:
        project_src: /home/malte/Projects/container/plex
        build: no
        pull: yes
        state: present
        restarted: yes
