---
- name: TVHeadend service
  hosts: serv
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
    - name: Start tvheadend service
      community.docker.docker_compose:
        project_src: /home/malte/Projects/container/tvheadend
        pull: yes
        state: present
        restarted: yes
