---
- name: upgrade unificontroller
  hosts: hassio
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
    - name: Pull new images
      community.general.docker_compose:
        project_src: /home/malte/unifi-controller
        pull: true
    - name: Restart container
      community.general.docker_compose:
        project_src: /home/malte/unifi-controller
        restarted: true
