---
- name: Install latest youtube-dl
  hosts: serv
  remote_user: ansible
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Download latest binary
    get_url:
      url: https://yt-dl.org/downloads/latest/youtube-dl
      dest: /usr/local/bin/youtube-dl
      mode: '755'
